apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "service.fullname" . }}
  labels: {{- include "service.labels" . | nindent 8 }}
  {{- with .Values.serviceLabels }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      {{- with .Values.args }}
      args: {{ . | toYaml | nindent 12 }}
      {{- end }}
      {{- with .Values.env }}
      env: {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.resources }}
      resources: {{- . | toYaml | nindent 12 }}
      {{- end }}