apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ include "inferenceService.fullname" . }}-disable-istio-sidecar
  annotations:
    policies.kyverno.io/title: Disable Istio Sidecar Injection
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/subject: Pod
spec:
  rules:
  - name: {{ include "inferenceService.fullname" . }}-disable-sidecar-injection
    match:
      any:
      - resources:
          kinds:
          - StatefulSet
          - Deployment
          selector:
            matchLabels:
              app.kubernetes.io/instance: {{ include "inferenceService.fullname" . }}
    mutate:
      patchStrategicMerge:
        spec:
          template:
            metadata:
              labels:
                sidecar.istio.io/inject: "false"