apiVersion: serving.kserve.io/v1beta1
kind: inferenceService
metadata:
  name: {{ include "inferenceService.fullname" . }}
  labels: {{- include "inferenceService.labels" . | nindent 8 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  annotations:
    {{- if .Values.metrics.enabled }}
    serving.kserve.io/enable-prometheus-scraping: "true"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      {{- with .Values.args }}
      args: {{ . | toYaml | nindent 12 }}
      {{- end }}
      {{- with .Values.env }}
      env: {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.resources }}
      resources: {{- . | toYaml | nindent 12 }}
      {{- end }}