fullnameOverride: ""

labels: {}

annotations: {}

## Create a secret with the Hugging Face token and use it as a secretKeyRef:
env:
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        name: hf-secret
        key: HF_TOKEN
        optional: false

args:
## Use the model_id of the KServe Hugging Face runtime to serve text generation 
## and text2text generation LLM models for faster time-to-first-token (TTFT) and 
## higher token generation throughput than the Hugging Face API.
  - --model_id=meta-llama/meta-llama-3-8b-instruct
  # - --model_id=deepseek-ai/deepseek-coder-7b-instruct-v1.5

resources:
  limits:
    cpu: "6"
    memory: 24Gi
    nvidia.com/gpu: "1"
  requests:
    cpu: "6"
    memory: 24Gi
    nvidia.com/gpu: "1"

metrics:
  enabled: false
  endpoints: []
    # - port: http-usermetric
    #   path: /metrics