apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: annotate-nodes  
spec:
  rules:
  - name: kwasm-annotate-nodes
    match:
      resources:
        kinds:
          - Node
        selector:
          matchLabels:
            lke.linode.com/pool-id: "xxxxxx"
        operations:
          - UPDATE
    mutate:
      targets:
      - apiVersion: v1
        kind: Node
        name: "{{request.object.metadata.name}}"
      patchStrategicMerge:
        metadata:
          annotations:
            kwasm.sh/kwasm-node: "true"